- name: demo of a variable
  hosts: localhost
  tasks:
    - name: print hello world
      ansible.builtin.debug:
        msg: hello world
    - name: print my name
      ansible.builtin.debug:
       msg: what is my name

- name: demo of a variable
  hosts: localhost
  vars:
   url: www.arsenal.com
  tasks:
  - name: print hello world
    ansible.builtin.debug:
     msg: "{{ url }}"
  - name: print hello world
    ansible.builtin.debug:
     msg: hello world